language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t insurance-node-backend 
      --build-arg DB_USERNAME="$DB_USERNAME"
      --build-arg DB_PASSWORD="$DB_PASSWORD"
      --build-arg DB_HOST="$DB_HOST"
      --build-arg DB_DB="$DB_DB"
      --build-arg PORT="$PORT"
      --build-arg HOST="$HOST"
      --build-arg ENV="$ENV" .
  - docker tag insurance-node-backend mayank071293/insurance-node-backend:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mayank071293/insurance-node-backend



