apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-node-backend
  labels:
    app: insurance-node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-node-backend
  template:
    metadata:
      labels:
        app: insurance-node-backend
    spec:
      containers:
      - name: api-users
        image: mayank071293/insurance-node-backend
        ports:
        - containerPort: 80