apiVersion: v1
kind: Service
metadata:
  name: insurance-node-backend
  labels:
    run: insurance-node-backend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: insurance-node-backend