apiVersion: v1
kind: Service
metadata:
  name: insurance_node_backend
  labels:
    run: insurance_node_backend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: insurance_node_backend